device: "cpu"
load_from_checkpoint: False
checkpoint_path: "checkpoints/2024_05_25_09_43_40/checkpoint_1490.pt"
save_dir: "checkpoints"

train:
  batch_size: 128
  epochs: 1500
  eval_every: 10
  teacher_ratio: 0.9
  save_every: 10
  data:
    dataset: "SineDataset"
    degree: 10
    num_functions: 1000
    num_points: 1000
    dt: 0.01
    mu: 1
    sigma: 5



optimizer:
  type: "adam"
  lr: 0.0001

model:
  rank: 32
  full: True

test:
  num_plots: 10
  context_length: 1000
  teacher_ratio: 0.9
  data:
    dataset: "SineDataset"
    degree: 10
    num_functions: 1000
    num_points: 1000
    dt: 0.01
    mu: 1
    sigma: 5
