device: "cpu"
load_from_checkpoint: False
checkpoint_path: "checkpoints/2021-06-01T14-00-00/"
save_dir: "checkpoints"

train:
  batch_size: 64
  epochs: 1000
  eval_every: 10
  teacher_ratio: 1.0
  save_every: 100
  data:
    dataset: "PolyDataset"
    degree: 10
    num_functions: 1000
    num_points: 1000
    dt: 0.01
    mu: 1
    sigma: 5



optimizer:
  type: "adam"
  lr: 0.003

model:
  rank: 10

test:
  num_plots: 10
  context_length: 1000
  teacher_ratio: 1.0
  data:
    dataset: "WhiteSignalDataset"
    degree: 10
    num_functions: 1000
    num_points: 1000
    dt: 0.01
    mu: 1
    sigma: 5
