device: "cpu"

data:
  degree: 10
  num_functions: 1000
  num_points: 1000

train:
  batch_size: 32
  epochs: 1000
  eval_every: 10


optimizer:
  type: "adam"
  lr: 0.01

model:
  rank: 10

test:
  num_plots: 10
  context_length: 500
