device: "cpu"
load_from_checkpoint: False
checkpoint_path: "checkpoints/2024_05_23_16_55_56/checkpoint_900.pt"
save_dir: "checkpoints"

data:
  degree: 10
  num_functions: 1000
  num_points: 1000

train:
  batch_size: 64
  epochs: 100000
  eval_every: 10
  teacher_ratio: 1.0
  save_every: 100


optimizer:
  type: "adam"
  lr: 0.003

model:
  rank: 10

test:
  num_plots: 10
  context_length: 500
  teacher_ratio: 0.5
