device: "cpu"
load_from_checkpoint: False
checkpoint_path: "checkpoints/2024_05_26_19_15_18/checkpoint_250.pt"
save_dir: "checkpoints"

train:
  batch_size: 128
  epochs: 2000
  eval_every: 20
  teacher_ratio: 1.0
  save_every: 20
  init_opt: False
  init_opt_AB: True
  basis_learnable: False
  data:
    dataset: "MixedDataset"
    degree: 15
    num_functions: 1000
    num_summands: 20
    max_frequency: 50
    num_points: 10000
    dt: 0.001
    mu: 1
    sigma: 5
  

  



optimizer:
  type: "adam"
  lr: 0.002
  weight_decay: 0.0

model:
  rank: 32
  full: False

test:
  num_plots: 1
  context_length: 10000
  teacher_ratio: 1.0
  data:
    dataset: ["LinearDataset", "MixedDataset", "VanDerPoolDataset", "FilteredNoiseDataset"]
    degree: 15
    num_functions: 1000
    num_summands: 20
    max_frequency: 50
    num_points: 10000
    dt: 0.001
    mu: 1
    sigma: 5
    alpha: 0.1
