device: "cpu"
load_from_checkpoint: False
checkpoint_path: "checkpoints/2024_05_26_19_15_18/checkpoint_250.pt"
save_dir: "checkpoints"

train:
  batch_size: 128
  epochs: 20000
  eval_every: 1
  teacher_ratio: 1
  save_every: 10
  init_opt: False
  basis_learnable: False
  data:
    dataset: "MixedDataset"
    degree: 60
    num_functions: 1000
    num_summands: 20
    max_frequency: 200
    num_points: 10000
    dt: 0.001
    mu: 1
    sigma: 5
  



optimizer:
  type: "adam"
  lr: 0.005

model:
  rank: 16
  full: False

test:
  num_plots: 1
  context_length: 10000
  teacher_ratio: 1.0
  data:
    dataset: "LegendreDataset"
    degree: 10
    num_functions: 1000
    num_points: 10000
    dt: 0.01
    mu: 1
    sigma: 5
